name: Maven PreRelease

on:
  push:
    branches: [ master ]

env:
  MAVEN_USER: ${{ secrets.MAVEN_USER }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USER: ZNotify

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: ZNotify/test-server-action@master

      - name: Get Kotlin version
        shell: bash
        run: node scripts/kotlin.js

      - name: Cache KotlinNative
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('build/kotlinVersion.txt') }}

      - uses: burrunan/gradle-cache-action@v1
        name: Release to Sonatype Snapshot and GitHub
        with:
          concurrent: true
          arguments: |
            build
            publishAllPublicationsToSonatypeRepository
            publishAllPublicationsToGithubRepository --scan
