name: Maven Release

on:
  release:
    types:
      - released

env:
  MAVEN_USER: ${{ secrets.MAVEN_USER }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'zulu'

      - uses: ZNotify/test-server-action@master

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build

      - name: Upload to Sonatype
        uses: gradle/gradle-build-action@main
        with:
          arguments: publishAllPublicationsToSonatypeRepository

      - name: Promote to Maven Central
        uses: gradle/gradle-build-action@main
        with:
          arguments: closeAndReleaseRepository
