name: Maven Release

on:
  release:
    types:
      - released

env:
  MAVEN_USER: ${{ secrets.MAVEN_USER }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USER: ZNotify

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: ZNotify/test-server-action@master

      - name: Get Kotlin version
        uses: gradle/gradle-build-action@main
        with:
          arguments: kotlinVersion

      - name: Cache KotlinNative
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('build/kotlinVersion.txt') }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository publishAllPublicationsToGithubRepository --scan

