name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        distribution: [ 'temurin', 'zulu' ]
        java_version: [ '11', '17', '18' ]
        include:
          - os: windows-latest
            distribution: temurin
            java_version: 18
          - os: macos-latest
            distribution: temurin
            java_version: 18
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ZNotify/kt-sdk'

      - uses: ZNotify/test-action@master

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java_version }}
          cache: 'gradle'

      - name: Install cURL
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          wget https://curl.se/download/curl-7.83.1.zip
          7z x curl-7.83.1.zip
          cd curl-7.83.1
          ./configure --with-openssl
          make
          sudo make install

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build

      - name: Run unit tests
        uses: gradle/gradle-build-action@main
        with:
          arguments: check