name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

env:
  TEST: true

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        distribution: [ 'temurin', 'zulu' ]
        java_version: [ '11', '17', '18' ]
        include:
          - os: windows-latest
            distribution: temurin
            java_version: 18
          - os: macos-latest
            distribution: temurin
            java_version: 18
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ZNotify/kt-sdk'

      - uses: ZNotify/test-action@master

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java_version }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: msys2/setup-msys2@v2
        if: ${{ runner.os == 'windows-latest' }}
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-curl
          path-type: inherit

      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build

      - name: Run unit tests on Windows
        shell: msys2 {0}
        if: ${{ runner.os == 'windows-latest' }}
        run: |
          export PATH=%PATH%:/c/msys64/mingw64/bin/
          ./gradlew check

      - name: Run unit tests
        if: ${{ matrix.os != 'windows-latest' }}
        uses: gradle/gradle-build-action@main
        with:
          arguments: check