name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

env:
  TEST: true

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ZNotify/kt-sdk'

      - uses: ZNotify/test-server-action@master

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Get Kotlin version
        shell: bash
        run: node scripts/kotlin.js

      - name: Cache KotlinNative
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('build/kotlinVersion.txt') }}

      - uses: burrunan/gradle-cache-action@v1
        name: Check
        with:
          concurrent: true
          arguments: check --scan
