name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

env:
  TEST: true

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ZNotify/kt-sdk'

      - uses: ZNotify/test-server-action@master

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Get Kotlin version
        run: node scripts/kotlin.js

      - name: Cache KotlinNative
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('build/kotlinVersion.txt') }}

      - name: Run unit tests
        uses: gradle/gradle-build-action@main
        with:
          arguments: check --scan