name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

env:
  TEST: true

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        distribution: [ 'temurin', 'zulu' ]
        java_version: [ '11', '17', '18' ]
        include:
          - os: macos-latest
            distribution: zulu
            java_version: 17
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ZNotify/kt-sdk'

      - uses: ZNotify/test-action@master

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java_version }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build

      - name: Run unit tests
        if: ${{ runner.os != 'Windows' }}
        uses: gradle/gradle-build-action@main
        with:
          arguments: check