name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

env:
  TEST: true

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        distribution: [ 'zulu' ]
        java_version: [ '17', '18' ]
        include:
          - os: macos-latest
            distribution: zulu
            java_version: 18
          - os: windows-latest
            distribution: zulu
            java_version: 18
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ZNotify/kt-sdk'

      - uses: ZNotify/test-server-action@master

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java_version }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/cache@v3
        with:
          path: ~/.konan/
          key: ${{ runner.os }}-konan-${{ hashFiles('**/build.gradle.kts') }}

      - name: Run unit tests
        uses: gradle/gradle-build-action@main
        with:
          arguments: check --scan